### ISSUE TITLE
Problem with urllib2

### ISSUE THREAD

**Issue by Tosible** [m-messiah/hulk#1]
Your script works, but if you capture the requests it sends using Wireshark, it says, "Connection: close" instead of "Connection: keep-alive". 
The problem is urllib2, they override the Connection header. 

Any fix for this? I looked online, but nothing.

**Comment by m-messiah** [comment]
Any of urllib\* libraries doesn't work with HTTP/1.1, so, you are right - keep-alive is useless here.
Fast searching does not bring me any worries to use requests library instead of urllib, so, I have updated script for using requests and take same bandwidth with more heavy load to server (in honor of keep-alive). Thanks.

**Comment by Tosible** [comment]
Will this work to bypass cookie authentication? 

import requests
url = 'http://github.com'
r = requests.get(url)
cookies = r.headers['Set-Cookie']
print cookies

I might be wrong.

**Comment by Tosible** [comment]
An example of what it prints: 

logged_in=no; domain=.github.com; path=/; expires=Wed, 30 Jan 2036 03:42:11 -0000; secure; HttpOnly, _gh_sess=eyJzZXNzaW9uX2lkIjoiMGU2ODFhNDMwYWE2ZDQ5YzllZjg2ZWNiNzkzMDliMTMiLCJfY3NyZl90b2tlbiI6Ijh1VnVqcDR1TnoxVHJyb25KMmlUMzlJUjl1ZHREdWd1Z1BIOGRvemNvb3M9In0%3D--82a9b1d1758676e30a0ade8c892cdded06923338; path=/; secure; HttpOnly
